### ISSUE TITLE
Errors when building with plugin

### ISSUE THREAD

**Issue by sweinertjr** [BranchMetrics/Branch-PhoneGap-Cordova-SDK#2]
Hi-

I am just having some issues when I build my Ionic app. All plugins seem to go fine, except the branch metrics plugin. It used to work okay, so it may be due to the iOS 8.2 upgrade. Check out my gist:

https://gist.github.com/sweinertjr/8d60c636dd045a8f02db

Thanks for your help.

**Comment by aaustin** [comment]
@sweinertjr uh oh - I just updated with a couple new referral functions. I wonder how it passed my build tests. Will get this resolve asap

**Comment by aaustin** [comment]
Hey @sweinertjr. After fixing some ugly bugs, I just pushed a new version to the central repo - can you check out the latest 0.4.1? Thanks!

**Comment by sweinertjr** [comment]
@aaustin I'll check this out first thing in the morning. Thanks for the quick response!

**Comment by sweinertjr** [comment]
@aaustin That did the trick! Thanks
