### ISSUE TITLE
Incorrect Android package import

### ISSUE THREAD

**Issue by jclalala** [BranchMetrics/Branch-PhoneGap-Cordova-SDK#3]
In CDVBranch.java:7, the import is:
import io.branch.referral.Branch.BranchError;

But the fully qualified class name for BranchError class is:
io.branch.referral.BranchError

The plugin won't compile, please see build log below:
.../platforms/android/src/io/branch/referral/CDVBranch.java:7: error: cannot find symbol
import io.branch.referral.Branch.BranchError;
symbol:   class BranchError
location: class Branch

**Comment by aaustin** [comment]
Hey @jclalala Sorry about that! Rolling out a fix to the repo and main cordova repo now. 

This version of the SDK was a weekend project that has turned into our production version. We're working on a completely revamped and native library right now, with a full test app that will be 100 times better. We'll make an announcement after it's ready

**Comment by jclalala** [comment]
Not a problem.

We may even be one of the early adoptor / testers.

Could you let me know an expected date for the improved version?

Also, would you want us to continue to log bugs for the current version?

- Jeff

**Comment by aaustin** [comment]
Please do tell me if you see any - I'll fix them right away. I'd say 3 weeks out for new version

**Comment by jclalala** [comment]
Ok will do :)

**Comment by jclalala** [comment]
So the build is still missing some classes:

 /workspace/hyperlocal/ionic-app/platforms/android/src/io/branch/referral/Base64.java:537:
error: cannot find symbol
         if (BuildConfig.DEBUG && (encoder.op != output_len))
             ^
   symbol:   variable BuildConfig
   location: class Base64

 /workspace/hyperlocal/ionic-app/platforms/android/src/io/branch/referral/Base64.java:720:
error: cannot find symbol

                 if (BuildConfig.DEBUG && (tailLen != 0 || p != len))

                     ^

   symbol:   variable BuildConfig

   location: class Encoder

 /workspace/hyperlocal/ionic-app/platforms/android/src/io/branch/referral/CDVBranch.java:248:
error: no suitable method found for loadRewards(<anonymous
BranchListResponseListener>)

             this.branch_.loadRewards(new BranchListResponseListener() {

                         ^

     method Branch.loadRewards(BranchReferralStateChangedListener) is not
applicable

       (actual argument <anonymous BranchListResponseListener> cannot be
converted to BranchReferralStateChangedListener by method invocation
conversion)

     method Branch.loadRewards() is not applicable

       (actual and formal argument lists differ in length)

 /workspace/hyperlocal/ionic-app/platforms/android/src/io/branch/referral/CDVBranch.java:264:
error: cannot find symbol

             if (args.size() > 0 && args.get(0) instanceof String) {

                     ^

   symbol:   method size()

   location: variable args of type JSONArray

 /workspace/hyperlocal/ionic-app/platforms/android/src/io/branch/referral/CDVBranch.java:265:
error: incompatible types

                 bucket = args.get(0);

                                  ^

   required: String

   found:    Object

 /workspace/hyperlocal/ionic-app/platforms/android/src/io/branch/referral/CDVBranch.java:270:
error: method getCredits in class Branch cannot be applied to given types;

             retParams.put("credits", this.branch_.getCredits(bucket));

                                                  ^

   required: no arguments

   found: String

   reason: actual and formal argument lists differ in length

 /workspace/hyperlocal/ionic-app/platforms/android/src/io/branch/referral/CDVBranch.java:278:
error: cannot find symbol

             if (args.size() > 1 && args.get(1) instanceof String) {

                     ^

   symbol:   method size()

   location: variable args of type JSONArray

 /workspace/hyperlocal/ionic-app/platforms/android/src/io/branch/referral/CDVBranch.java:279:
error: incompatible types

                 amount = args.get(0);

                                  ^

   required: int

   found:    Object

 /workspace/hyperlocal/ionic-app/platforms/android/src/io/branch/referral/CDVBranch.java:280:
error: incompatible types

                 bucket = args.get(1);

                                  ^

   required: String
   found:    Object
 /workspace/hyperlocal/ionic-app/platforms/android/src/io/branch/referral/CDVBranch.java:282:
error: 'void' type not allowed here
             retParams.put("count", this.branch_.redeemRewards(bucket,
amount));
                                                              ^
 /workspace/hyperlocal/ionic-app/platforms/android/src/io/branch/referral/CDVBranch.java:282:
error: cannot find symbol
             retParams.put("count", this.branch_.redeemRewards(bucket,
amount));

             ^

   symbol:   variable retParams

   location: class CDVBranch

 /workspace/hyperlocal/ionic-app/platforms/android/src/io/branch/referral/CDVBranch.java:288:
error: variable action is already defined in method
execute(String,JSONArray,CallbackContext)

             String action = "";

                    ^

 /workspace/hyperlocal/ionic-app/platforms/android/src/io/branch/referral/CDVBranch.java:289:
error: cannot find symbol

             if (args.size() > 0 && args.get(0) instanceof String) {

                     ^

   symbol:   method size()

   location: variable args of type JSONArray

 /workspace/hyperlocal/ionic-app/platforms/android/src/io/branch/referral/CDVBranch.java:290:
error: incompatible types

                 action = args.get(0);

                                  ^

   required: String

   found:    Object

 /workspace/hyperlocal/ionic-app/platforms/android/src/io/branch/referral/CDVBranch.java:299:
error: variable action is already defined in method
execute(String,JSONArray,CallbackContext)

             String action = "";

                    ^

 /workspace/hyperlocal/ionic-app/platforms/android/src/io/branch/referral/CDVBranch.java:300:
error: cannot find symbol

             if (args.size() > 0 && args.get(0) instanceof String) {

                     ^

   symbol:   method size()

   location: variable args of type JSONArray

 /workspace/hyperlocal/ionic-app/platforms/android/src/io/branch/referral/CDVBranch.java:301:
error: incompatible types

                 action = args.get(0);

                                  ^

   required: String

   found:    Object

 Note: Some input files use or override a deprecated API.

 Note: Recompile with -Xlint:deprecation for details.

 17 errors

**Comment by aaustin** [comment]
Fix incoming!

**Comment by aaustin** [comment]
@jclalala I updated it with all those fixes - man that was embarrassing. I didn't increment the version this time - see if it will update?

**Comment by jclalala** [comment]
So it is still missing the BuildConfig class. I believe it should either be
a private static inner class (which I don't find in Base64 class) or
perhaps you simply forgot to push that file?

**Comment by aaustin** [comment]
I deleted the reference to it - that was for a new automated test suite we're using. Is it asking for it?

**Comment by aaustin** [comment]
Oops didn't update the repo, only the Cordova repo. Just did here https://github.com/BranchMetrics/Branch-PhoneGap-Cordova-SDK/commit/7711aa1b2219a06964b30a95cf479695557d89f9

**Comment by jclalala** [comment]
Let me check. Maybe my plugin didn't reload, I'll delete it and run our
build again. Will let you know.

**Comment by aaustin** [comment]
Hmm - I bet it's because I didn't increment the version. I'll do that now just in case anyone else downloaded this recently

**Comment by jclalala** [comment]
Ok compile passed.

...

:CordovaLib:build

BUILD SUCCESSFUL

Btw, we sincerely appreciate your hardwork and quick response.

I will close this issue now.

**Comment by aaustin** [comment]
Sorry for my typos :(
