### ISSUE TITLE
IGNORE_UA_STRING is never defined

### ISSUE THREAD

**Issue by EwyynTomato** [BranchMetrics/Branch-PhoneGap-Cordova-SDK#5]
Affected version: 0.4.8

Compiler error:
    BNCLinkData.m:90:52: error: use of undeclared identifier 'IGNORE_UA_STRING'

As per [search](https://github.com/BranchMetrics/Branch-PhoneGap-Cordova-SDK/search?utf8=%E2%9C%93&q=IGNORE_UA_STRING), IGNORE_UA_STRING is never defined. Missed the commit, perhaps?

**Comment by aaustin** [comment]
@EwyynTomato Thanks so much for pointing this out. I tried to update the core SDK but it seems like only some of the files were actually updated :(

I just pushed out 4.9 where I reupdated each file. It seems to have gone through this time!

**Comment by aaustin** [comment]
Sorry about the hassle

**Comment by EwyynTomato** [comment]
My apologies for the late reply, it compiles fine now.

Thank you!
