### ISSUE TITLE
iOS implementation

### ISSUE THREAD

**Issue by Deminetix** [BranchMetrics/Branch-PhoneGap-Cordova-SDK#7]
It looks as though the android lib uses the key supplied to `Branch.getInstance("YOURKEY", cb)` but the iOS lib does not. It errors saying "Are you sure you used the right key".

I then had a look the native iOS repo's README which states to put `branch_key` in the p-list but that didn't work, then i found the cordova lib uses the p-list key `bnc_app_key` but i couldn't find it documented anywhere. Using this entry made everything work perfectly.

Is it easy for anyone to make the `getInstance` method work the same as on android? We would like our javascript libraries to control switching between test/live keys centrally. If not, i'll have to revisit this later and help out with a pull-request.

**Comment by aaustin** [comment]
@Deminetix Oops - I had forgotten to publish my changes to the repo. I checked local github and saw them all sitting there. See: https://github.com/BranchMetrics/Branch-PhoneGap-Cordova-SDK/commit/405d9451fdc593852194e52d6bdd9aab75f9fe08

**Comment by aaustin** [comment]
Most of the time, folks were just using the Cordova library so they didn't noticed the broken repo.
http://plugins.cordova.io/#/package/io.branchmetrics.branchreferral

**Comment by Deminetix** [comment]
@aaustin that's a lot of changes. Are there any major changes? And does this now support the apiKey passed in from JavaScript?

**Comment by aaustin** [comment]
Here's a high level summary:
1. Adds support for the branch_key parameter (your issue)
2. Fixes a bug related to us determining if the app was an update vs fresh install
3. Fixes a bug associated with a share sheet on iOS robotically clicking our links

**Comment by keithdmoore** [comment]
Has this issued been resolved?

**Comment by Deminetix** [comment]
Sorry, yeah this is resolved with @aaustin commit
